version: "3.9"
services:
  app:
    build: ./infra/java
    ports:
      - 8080:8080
    volumes:
      - ./sample1:/workspace
    working_dir: /workspace
    tty: true

  db:
    build: ./infra/mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: "%"
      TZ: ${TZ}
    volumes:
      - db:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  db:
